version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /home/homeassistant/.homeassistant/ha_service:/config
    environment:
      - TZ=Europe/Warsaw
    restart: always
    network_mode: host